services:
  bot:
    build: .
    container_name: itoq_advokat_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./documents:/app/documents
    networks:
      - bot_network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  bot_network:
    driver: bridge 